version: 2

models:
  - name: gold_account_usage_daily
    description: "Daily account usage mart (account_id x day)."
    columns:
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_users')
              field: account_id

      - name: date
        tests:
          - not_null

      - name: account_day_key
        tests:
          - not_null
          - unique

  - name: gold_account_engagement_monthly
    description: "Monthly account engagement mart (account_id x month)."
    columns:
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_users')
              field: account_id

      - name: month
        tests:
          - not_null

      - name: account_month_key
        tests:
          - not_null
          - unique
          
  - name: gold_mrr_monthly
    description: "Account-level monthly recurring revenue (account_id x month)."
    columns:
      - name: month
        tests: [not_null]
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_subscriptions')
              field: account_id
      - name: mrr
        tests: [not_null]
      - name: account_month_key
        tests: [not_null, unique]

  - name: gold_nrr_bridge_monthly
    description: "NRR bridge components by account and month derived from gold_mrr_monthly."
    columns:
      - name: account_month_key
        tests:
          - unique
          - not_null
      - name: month
        tests:
          - not_null
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_users')
              field: account_id
      - name: starting_mrr
        tests:
          - not_null
      - name: ending_mrr
        tests:
          - not_null

  - name: gold_nrr_monthly
    description: "Portfolio-level NRR/GRR rollup by month."
    columns:
      - name: month
        tests:
          - unique
          - not_null
      - name: starting_mrr_total
        tests:
          - not_null
      - name: ending_mrr_for_nrr_total
        tests:
          - not_null