version: 2

models:
  - name: silver_users
    description: "Conformed users entity (1 row per user_id), typed and deduplicated."
    columns:
      - name: user_id
        tests: [not_null, unique]
      - name: account_id
        tests: [not_null]
      - name: email
        tests: [not_null]

  - name: silver_events
    description: "Conformed events stream, typed and incrementally appended."
    columns:
      - name: event_id
        tests: [not_null, unique]
      - name: user_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_users')
              field: user_id
      - name: event_ts
        tests: [not_null]
        
  - name: silver_subscriptions
    description: "Conformed subscriptions entity (1 row per subscription_id)."
    columns:
      - name: subscription_id
        tests: [not_null, unique]
      - name: account_id
        tests: [not_null]
      - name: monthly_price
        tests: [not_null]

  - name: silver_invoices
    description: "Conformed invoices entity (1 row per invoice_id)."
    columns:
      - name: invoice_id
        tests: [not_null, unique]
      - name: subscription_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_subscriptions')
              field: subscription_id
      - name: account_id
        tests: [not_null]
      - name: invoice_date
        tests: [not_null]
      - name: amount
        tests: [not_null]