version: 2

models:
  - name: silver_users
    description: "Conformed users entity (1 row per user_id), typed and deduplicated."
    columns:
      - name: user_id
        tests: [not_null, unique]
      - name: account_id
        tests: [not_null]
      - name: email
        tests: [not_null]

  - name: silver_events
    description: "Conformed events stream, typed and incrementally appended."
    columns:
      - name: event_id
        tests: [not_null, unique]
      - name: user_id
        tests:
          - not_null
          - relationships:
              to: ref('silver_users')
              field: user_id
      - name: event_ts
        tests: [not_null]